#include "types.h"

// sarali varisai

const typedef struct sarali_varisai {
  const char *aarohana;
  const char *avarohana;
} sarali_varisai;

const sarali_varisai sarali[15] = {
    {"SRGMPDNS.","S.NDPMGRS"},
    {"SRSRSRGMSRGMPDNS.","S.NS.NS.NDPS.NDPMGRS"},
    {"SRGSRGSRSRGMPDNS.","S.NDS.NDS.NS.NDPMGRS"},
    {"SRGMSRGMSRGMPDNS.","S.NDPS.NDPS.NDPMGRS"},
    {"SRGMSRGMSRSRSRGMSRGMPDNS.","S.NDPS.NDPS.NS.NS.NDPS.NDPMGRS"},
    {"SRGMP,SRSRGMPDNS.","S.NDPM,S.NS.NDPMGRS"},
    {"SRGMPPSRSRGMPDNS.","S.NDPMMS.NS.NDPMGRS"},
    {"SRGMPDSRSRGMPDNS.","S.NDPMGS.NS.NDPMGRS"},
    {"SRGMPMGRSRGMPDNS.","S.NDPMPDNS.NDPMGRS"},
    {"SRGMPMDPSRGMPDNS.","S.NDPMPGMS.NDPMGRS"},
    {"SRGMP,GMP,,,P,,,GMPDNDPMGMPGMGRS",","},
    {"S.,NDN,DPD,PMP,P,GMPDNDPMGMPGMGRS",","},
    {"S.S.NDNNDPDDPMP,P,GMPDNDPMGMPGMGRS",","},
    {"SRGRG,GMPMP,DPD,MPDPDNDPMPDPMGRS",","},
    {"SRGMP,P,DDP,MMP,DNS.,S.NDPS.NDPMGRS",","}
};